# Generated by Django 3.0.7 on 2022-11-19 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pic/CustomerProfilePic/'),
            preserve_default=False,
        ),
    ]
